version: "3.19"
services: 
  postgres:
    image: postgres:16
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "5432:5432"

  backend:
    image: hugocbb/gerenciador-tarefas-backend:1.0
    ports:
      - "8000:8000"

  frontend:
    image: hugocbb/gerenciador-tarefas-frontend:1.0
    ports:
      - "5173:5173"
